tinyMCE.addI18n('eu.advimage_dlg',{
tab_general:"Orokorra",
tab_appearance:"Itxura",
tab_advanced:"Aurreratua",
general:"Orokorra",
title:"Izenburua",
preview:"Aurrebista",
constrain_proportions:"Itxura-erlazioa blokeatu",
langdir:"Hizkuntzaren norabidea",
langcode:"Hizkuntza-kodea",
long_desc:"Deskribapen luzea",
style:"Estiloak",
classes:"Klaseak",
ltr:"Ezkerretik eskumara",
rtl:"Eskumatik ezkerrera",
id:"Id",
map:"Irudi-mapa",
swap_image:"Irudia ordezkatu",
alt_image:"Ordezko irudia",
mouseover:"Xagua gainean dagoenean",
mouseout:"Xagua gainetik kentzean",
misc:"Besteak",
example_img:"Irudiaren aurebista",
missing_alt:"Deskribapenik sartu gabe jarraitu nahi duzu? Horrela irudia ez da irisgarria izango ezgaitasunen bat izan edo testu-nabigatzaileak darabiltzatenentzat.",
dialog_title:"Irudia txertatu/editatu",
src:"Irudiaren helbidea",
alt:"Irudiaren deskribapena",
list:"Irudi-zerrenda",
border:"Inguruko marra",
dimensions:"Tamainak",
vspace:"Tarte bertikala",
hspace:"Tarte horizontala",
align:"Alineazioa",
align_baseline:"Oinarri-lerroa",
align_top:"Gainean",
align_middle:"Tartean",
align_bottom:"Azpian",
align_texttop:"Testua gainean",
align_textbottom:"Testua azpian",
align_left:"Ezkerrean",
align_right:"Eskuman",
image_list:"Irudi-zerrenda"
});