tinyMCE.addI18n('eu.advlink_dlg',{
title:"Lotura txertatu/editatu",
url:"Loturaren URL helbidea",
target:"Helburua",
titlefield:"Izenburua",
is_email:"Sartutako helbideak e-posta bat dirudi, aurretik mailto: gehitzea nahi duzu?",
is_external:"Sartutako helbideak kanpoko webgune batena dirudi, aurretik http:// gehitzea nahi duzu?",
list:"Loturen zerrenda",
general_tab:"Orokorra",
popup_tab:"Pop-up leihoa",
events_tab:"Ebentuak",
advanced_tab:"Aurreratua",
general_props:"Aukera orokorrak",
popup_props:"Pop-up leihoen aukerak",
event_props:"Ebentuen aukerak",
advanced_props:"Aukera aurreratuak",
popup_opts:"Aukerak",
anchor_names:"Aingurak",
target_same:"Leiho honetan ireki",
target_parent:"Leiho-gurasoan ireki",
target_top:"Gorengo leihoan ireki",
target_blank:"Leiho berrian ireki",
popup:"Javascript bidezko pop-up",
popup_url:"Pop-up leihoaren URL helbidea",
popup_name:"Pop-uparen izena",
popup_return:"'return false' txertatu",
popup_scrollbars:"Desplazamendu barrak",
popup_statusbar:"Egoera barra",
popup_toolbar:"Tresna barra",
popup_menubar:"Menu barra",
popup_location:"Helbide-barra",
popup_resizable:"Leihoaren tamaina aldatzen utzi",
popup_dependent:"Menpekoak (Mozilla/Firefox bakarrik)",
popup_size:"Tamaina",
popup_position:"Posizioa (X/Y)",
id:"Id",
style:"Estiloa",
classes:"Klaseak",
target_name:"Helburuaren izena",
langdir:"Hizkuntzaren zentzua",
target_langcode:"Helburuaren hizkuntza",
langcode:"Hizkuntza-kodea",
encoding:"Helburuaren karaktere-kodifikazioa",
mime:"Helburuaren MIME Mota",
rel:"rel etiketa",
rev:"Helburuaren orrialdearekiko erlazioa",
tabindex:"Tabulazio-indizea",
accesskey:"Sarrera-tekla",
ltr:"Ezkerretik eskumara",
rtl:"Eskumatik ezkerrera",
link_list:"Loturen zerrenda"
});